name: Bug Report
description: Report a bug or issue to help us improve.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please provide as much detail as possible to ensure we can address the issue effectively.
  - type: dropdown
    id: macos-version
    attributes:
      label: macOS Version
      multiple: false
      options:
        - Sequoia (15.x)
        - Sonoma (14.x)
        - Ventura (13.x)
        - Monterey (12.x)
        - Big Sur (11.x)
        - Catalina (10.15)
        - Mojave (10.14)
        - Other
    validations:
      required: true
  - type: input
    id: macos-version-specific
    attributes:
      label: Specific macOS Version
      description: Enter your exact macOS version (e.g., 15.1.1, 14.2.1).
      placeholder: e.g., 15.1.1, 14.2.1
    validations:
      required: true
  - type: dropdown
    id: mac-architecture
    attributes:
      label: Mac Processor Type
      multiple: false
      options:
        - Apple Silicon / ARM
        - Intel / x86
    validations:
      required: true
  - type: input
    id: macutil-version
    attributes:
      label: macutil Version
      description: macutil version (found above the list within macutil).
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      multiple: false
      description: Specify the branch of the project you are using.
      options:
        - main 
        - prerelease
        - stable 
        - other
    validations:
      required: true
  - type: input
    id: specify-branch
    attributes:
      label: Specify Branch (if "Other" selected)
      description: Enter the branch name.
      placeholder: e.g., feature/new-feature
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide a clear and concise description of the bug or issue.
      placeholder: Describe the issue in detail.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Tried to use script '...'
        2. It ran until this point '...'
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: |
        What actually happened when you followed the reproduction steps.
      placeholder: Describe what actually occurred.
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: |
        A clear and concise description of what you expected to happen.
      placeholder: Explain the expected outcome.
    validations:
      required: true
  - type: textarea
    id: supporting-information
    attributes:
      label: Supporting Information
      description: |
        Add any other context, logs, error messages, screenshots, or configurations that might help diagnose the issue.
      placeholder: Include any related logs, error messages, screenshots, or configurations.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked for duplicate issues.
        - label: I checked existing discussions.
        - label: This issue is not included in the roadmap.
        - label: This issue is present on both stable and development branches.
          required: true

