name = "System Setup"

[[data]]
name = "System Tools"

[[data.entries]]
name = "Development Setup"
description = "This script is designed to handle the installation of various development dependencies and tools across different Linux distributions"
script = "dev-setup.sh"

[[data.entries]]
name = "Full System Cleanup"
description = "This script is designed to remove unnecessary packages, clean old cache files, remove temporary files, and to empty the trash."
script = "system-cleanup.sh"

[[data.entries]]
name = "Fix Finder"
description = "Finder optimizations for people without a mental disorder."
script = "fix-finder.sh"

[[data.entries]]
name = "Remove Animations"
description = "This script is designed to remove snap packages and the snapd service from your system"
script = "remove-animations.sh"

[[data.entries]]
name = "AltTab"
description = "AltTab brings Windows-like Alt+Tab functionality to macOS, allowing you to switch between individual windows instead of just applications. Perfect for users who work with multiple windows of the same application."
script = "alttab-setup.sh"